SEARCHES = [
    '"Data-Platform-Engineer"-AND-Remote',
    'Data-Platform-Engineer-AND-Remote',
    '"Data-Platform"-AND-Remote',
    'Data-Platform-AND-Remote',
    'baseline-AND-remote-AND-data',
    'nv1-AND-remote-AND-data',
    'remote-AND-"data-engineer"',
    'remote-AND-data',
    'Data-Platform-Engineer',
    'Data-Platform',
    '"Data-Architect"',
    '"Data-Engineer"',
    'AI',
    'ML',
    'python',
]